---
title: "Simulation of IHPP for Wiebull intensity function"
author: "4 MA"
date: "2025/2026"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r simulPPh,eval=FALSE}
simulHPP <- function(lambda, Tmax) {
  N <- rpois(1, lambda * Tmax)
  U <- runif(N, 0, Tmax)
  return(sort(U))
}
```

```{r plot.PP}
plot.PP<- function(PP)
{
# plot the counting process (with jumps of size 1 (starting at point (0,0))):
plot(c(0,PP),0:length(PP),type="s",xlab="time t",ylab="number of events by time t")
# add the arrival times on the horizontal axis:
points(PP,0*PP,type="p",pch=16)
# link arrival times with the counts:
lines(PP,0:(length(PP)-1),type="h",lty=2)
}
```

# 1 - Inhomogeneous Poisson processes

Simulation of an inhomogeneous Poisson processes with given intensity function `lambda_fct` on a fixed window \[0,`Tmax`\].

```{r simulPPi,eval=FALSE}
simulPPi = function(lambda_fct,Tmax,M)
{
  M= lambda_fct(Tmax)
  res = NULL
  PPh <- simulHPP(M, Tmax)
  U <- runif(length(PPh),0,M)
  for (i in 1:length(PPh)){
    if (U[i]< lambda_fct(PPh[i]))
      {
      res <- append(res, PPh[i])
    }
  }
    return(sort(res))
  }
```

### NHPP Simulation

```{r simu, eval=FALSE, warning=TRUE}

simulWeibull <- function(beta, theta, Tmax) {
  M <- (beta/theta) * (Tmax/theta)^(beta-1)
  
  PPh <- simulPPh1(M, Tmax)
  
  U <- runif(length(PPh), 0, M)
  lambda_t <- (beta/theta) * (PPh/theta)^(beta-1)
  res <- PPh[U < lambda_t]
  return(res)
}



Tmax=100

 
lambda_fct1 <- function(x){
  beta = 1.09
  teta = 1
  return((beta/teta)*(x/teta)^(beta-1))}



PPi1 = simulPPi(lambda_fct1, Tmax)

plot(PPi1)
```

## Crow

```{r lambda1,eval=FALSE}


# plot:
par(mfrow=c(1,2))
plot.PP(PPi1)
curve(lambda_fct1,from=0,to=Tmax,n=1000)

```

### Test Statistic :

```{r teststat,eval=FALSE}

testCrow <- function(PP, Tmax, silent = FALSE)
{
  n <- length(PP)
  
  stat_test_Obs = 2 * sum(log(Tmax / PP)) 
  
  p_value <- pchisq(stat_test_Obs, 2 * n)
  
  if (!silent) {
    print(paste("The Observed Crow Statistic is : ", stat_test_Obs))
    print(paste("The p-value : ", p_value))
    
    if (p_value < 0.05) {
      print("Conclusion: we reject H0 at level 5%, Beta is greater than 1")
    } else {
      print("Conclusion: we do not reject H0 at level 5%, Beta could be 1")
    }
  }

  return(p_value)
}





```

## Barlow

### Test Statistic :

```{r}

testBarlow <- function(PP, Tmax, silent = FALSE)
{
  n = length(PP)
  if (n < 4) return(NA) 
  
  d = floor(n/2)
  
  stat_test_Obs = ((n - d) * PP[d]) / (d * (PP[n] - PP[d]))
  
  p_value <- 1 - pf(stat_test_Obs, 2 * d, 2 * (n - d))
  
  if (!silent) {
    print(paste("The Observed test Statistic is : ", stat_test_Obs))
    print(paste("The p-value : ", p_value))
    
    if (p_value < 0.05) {
      print("Conclusion: we reject H0 at level 5%, Beta is greater than 1")
    } else {
      print("Conclusion: we do not reject H0 at level 5%, data suggests Beta could be 1")
    }
  }

  return(p_value)
}






```

```{r}
print("Barlow")

testBarlow(PPSimu,Tmax)

print("Crow")
testCrow(PPSimu,Tmax)

```

# Power Comparaison

```{r}
plot_puissance <- function(Tmax, liste_beta, nsimu) {
  plot(NULL, xlim=range(liste_beta), ylim=c(0,1), 
       xlab="Beta", ylab="Power",
       main="Crow vs Barlow")
  
  abline(h=0.05, col="red", lty=2)

  for(b in liste_beta) {
    
    rejet_crow = 0
    rejet_barlow = 0
    
    for(i in 1:nsimu) {
      donnees <- simulWeibull(beta = b, theta = 1, Tmax = Tmax)
      
      p_c <- testCrow(donnees, Tmax, silent = TRUE)
      p_b <- testBarlow(donnees, Tmax, silent = TRUE)
      
      if(!is.na(p_c) && p_c < 0.05) rejet_crow = rejet_crow + 1
      if(!is.na(p_b) && p_b < 0.05) rejet_barlow = rejet_barlow + 1
    }
    
    puissance_C = rejet_crow / nsimu
    puissance_B = rejet_barlow / nsimu
    
    points(b, puissance_C, col="blue", pch=19) 
    points(b, puissance_B, col="red", pch=17) 
  }
  
  legend("bottomright", legend=c("Crow", "Barlow"), col=c("blue", "red"), pch=c(19, 17))
}
```

```{r}
betas_test <- c(seq(1, 1.5, by = 0.01), seq(1.5, 2, by = 0.1) )
plot_puissance(Tmax = 100, betas_test, 100)
```